// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Reservation = __t.object("Reservation", {
  id: __t.u64(),
  spotId: __t.u32(),
  date: __t.string(),
  occupant: __t.string(),
});
export type Reservation = __Infer<typeof Reservation>;

export const Spot = __t.object("Spot", {
  id: __t.u32(),
  name: __t.string(),
  sortOrder: __t.u32(),
});
export type Spot = __Infer<typeof Spot>;

