// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelReservationReducer from "../cancel_reservation_reducer";
import QuickReserveReducer from "../quick_reserve_reducer";
import ReserveSpotReducer from "../reserve_spot_reducer";
import SeedSpotsReducer from "../seed_spots_reducer";

export type CancelReservationParams = __Infer<typeof CancelReservationReducer>;
export type QuickReserveParams = __Infer<typeof QuickReserveReducer>;
export type ReserveSpotParams = __Infer<typeof ReserveSpotReducer>;
export type SeedSpotsParams = __Infer<typeof SeedSpotsReducer>;

